FROM node:18.17-buster-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Install Node Package
RUN pnpm install --shamefully-hoist
RUN pnpm add cross-env

# Set Env
ENV NODE_ENV development

# Cmd script
CMD ["pnpm", "run", "start:dev"]
