FROM node:18.17-buster-slim as builder

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

# Dev bağımlılıkları da dahil olmak üzere tüm bağımlılıkları yükle
RUN npm install -g pnpm && pnpm install --frozen-lockfile

COPY . .

# Uygulamayı derle
RUN pnpm run build

# Yeni bir aşama başlat
FROM node:18.17-buster-slim

WORKDIR /app

# Sadece gerekli dosyaları kopyala
COPY --from=builder /app/package.json /app/pnpm-lock.yaml ./
COPY --from=builder /app/dist ./dist

# Sadece prodüksiyon bağımlılıklarını yükle
RUN npm install -g pnpm && pnpm install --prod --frozen-lockfile

ENV NODE_ENV production

EXPOSE 3000

# Uygulamayı başlat
CMD ["node", "dist/src/index.js"]